### ISSUE TITLE
Using round in "R/crosstab.R"

### ISSUE THREAD

**Issue by vfoss** [jalvesaq/descr#7]
Just curious: why do you opt to use the round function (line 59) in the crosstab function? (https://github.com/cran/descr/blob/master/R/crosstab.R)
It renders the entire function unusable if the weights vector contains decimals.  Could you edit this to make "round" a boolean argument in the main crosstab function instead? Thanks! 
(If you prefer I can make a pull request.)

**Comment by jalvesaq** [comment]
What will be the name of the argument? It can't be `round` because this is the name of the function to be called if the value of the argument is `TRUE`.

What will be the default value of the argument? PSPP 0.10.2 does not round the frequencies by default, only if the user explicitly puts in the script `/COUNT = ROUND`. So, I think we could follow PSPP and do not round the frequencies by default. Please, see: https://www.gnu.org/software/pspp/manual/html_node/CROSSTABS.html

One possibility would be the name of the argument to be `count` and its default value to be `c("asis", "round", "truncate")`. Then, we could check

```
if(is.character(count) && count[1] == "round")
```
etc...

I prefer if you make the pull request because the original idea was yours.

**Comment by vfoss** [comment]
Excellent, I will play around with this and hopefully can send a pull request within the next few weeks.

**Comment by jalvesaq** [comment]
Did you look at the option `digits`? Please, see CrossTable's documentation.
